### PR TITLE
[aesthetics] Toon Shader and Character Emission

### LINKED ISSUE #339: Research: Unity Shader Graph
- Shader Graph in general
- How to make soft outline shader in unity
- Characters self ilumination shader (NPR Shader?)
- Integrate objects from sketchfab to unity

### LINKED ISSUE #340: Living Room: Adjust texture materials
- Roughness
- Smoothness

Note: In Unity

### PR DESCRIPTION
**Pull request by JahnsMichael**
### Main changes

- add toon shading
- add character emission
- [shader graph docs](https://docs.google.com/document/d/1bPMelH8Yv3t3GQdIGQe0T8IoBD9tGVYvzpaN-dSgx0U/edit?usp=sharing)

### Tasks List

- [close #340]
- [close #339]

### Attachments

Scene: Assets/_Developers/Jahns/HouseAbigail_FixedBuilding 1.unity

https://user-images.githubusercontent.com/60375650/173032547-24656d30-e638-4130-bb41-7c8ebbcda43f.mp4

### New Packages

- it is not a new package but please check URP settings under the URP directory if you find any issues. The known issue is that sprite 2d doesn't work with the toon shader because it has no depth. Please adjust the URP settings, in the Toon Shading config, change the Event dropdown.

### CODE REVIEW

**Review by ahmadhaydar — APPROVED** [review]
Looks good to me, may need sum experiments on that to find what's lookin right

**Review by uciii — APPROVED** [review]
Cool!

**Review by uciii — CHANGES_REQUESTED** [review]
tes

**Comment by JahnsMichael** [comment]
> Fix issue buat tanda seru di light switch gk nongol, tapi di item nongol

Fixed with the last commit

image

**Pull request merged**
