### PR TITLE
[feature] Adjust Light Switch SFX

### LINKED ISSUE #42: Adjust Light Switch Audio Distance
Make sure there is graph progression in SFX based on distance from source to player's position

### LINKED ISSUE #70: Adjust SFX Light Switch

### PR DESCRIPTION
**Pull request by RaiRiz**
Set SFX for Light Switch and the distance effect

### Main changes
Add sfx for light switch on and off and adjust effect based on player distance from light switch source

### Tasks List
- [close #42 ]
- [close #70 ]

### Attachments
- light switch on

https://user-images.githubusercontent.com/55452897/149525218-803b74a4-e9f8-4369-a6f9-546823f3e9b7.mp4

- light switch off

https://user-images.githubusercontent.com/55452897/149525470-2f814f76-f449-487c-a5b5-81ae15988c92.mp4

### CODE REVIEW

**Review by rafiftaris — APPROVED** [review]
Even though the radius is still to big imo, it can be balanced later. LGTM!

**Review by rafiftaris — CHANGES_REQUESTED** [review]
Implement SFX with audio manager after #81 merged

**Review by rafiftaris — APPROVED** [review]
Revision: this PR will merged before #81 and @naufalhilmi12345 will implement the SFX through audio manager

**Review by naufalhilmi12345 — APPROVED** [review]
LGTM!

**Pull request merged**
