### PR TITLE
[feature] Implement audio exorcism type 1

### LINKED ISSUE #198: Implement exorcism SFX burning

### LINKED ISSUE #236: Implement audio meatball seller

### LINKED ISSUE #238: Implement audio silence empty room

### PR DESCRIPTION
**Pull request by RaiRiz**
find and design audio for exorcism type 1 (burn the ghost)

### Main changes

as stated above

### Tasks List

- [close #198 ]
- [close #236 ]
- [close #238 ]

### Attachments

image

image

image

Exorcism type 1 male: https://discord.com/channels/918510403909214268/918514897422258216/948972073794039828

Exorcism type 1 female: https://discord.com/channels/918510403909214268/918514897422258216/949473856026992660

Silence room ambience: https://discord.com/channels/918510403909214268/918514897422258216/949487873416110202 (the last one)

Meatball seller: https://discord.com/channels/918510403909214268/918514897422258216/949484532921417758

### CODE REVIEW

**Review by uciii — COMMENTED** [review]
For naming, IMO instead of SFX_[Male/Female]Exorcism[X]\_[Y] (X Y = number), it would be intuitive with SFX_Exorcism_[Old/Young][Male/Female]_[X]

It is because when we want to search this audio, the focus is on “exorcism”, so place it first. Then for the version, I think 1 number is enough, we can differentiate between old and young instead.

**Comment by RaiRiz** [comment]
accepted the advice, kindly re-check!

**Review by VadimBhirawa — APPROVED** [review]
"Sounds" good!

**Review by uciii — APPROVED** [review]
Gud!

**Pull request merged**
