### PR TITLE
[aesthetics] Sofa & LightBulb

### LINKED ISSUE #90: [3D Object] Light Bulb in Ceiling

### LINKED ISSUE #92: [3D Object] Sofa

### PR DESCRIPTION
**Pull request by JahnsMichael**
### Main changes

- add LightBulb model and materials
- add Sofa model, materials, and textures

### Tasks List

- [close #90]
- [close #92]

### Attachments

- LightBulb

LightBulb

- Sofa

https://user-images.githubusercontent.com/60375650/150478285-b61f418c-ace1-405d-85a6-8098ffbc62d3.mp4

### CODE REVIEW

**Comment by raihansyahdean** [comment]
Titip modif di Readme dong Jahns hehe.
- 5.3 Effects -> Asset Type VOL jadiin Volume
- 4. Project Hierarchy -> Sections -> 4.3 Character jadiin 4.3 Characters

**Comment by JahnsMichael** [comment]
> Titip modif di Readme dong Jahns hehe. 5.3 Effects -> Asset Type VOL jadiin Volume 4. Project Hierarchy -> Sections -> 4.3 Character jadiin 4.3 Characters

Done @raihansyahdean

**Comment by uciii** [comment]
And don't forget to add it in [3D Mesh List](https://docs.google.com/spreadsheets/d/1uGEMDAMG0gg0ye39r2UNICfS8tpuOsGJXS7MlWKUVZk/edit#gid=0)

**Comment by JahnsMichael** [comment]
> And don't forget to add it in [3D Mesh List](https://docs.google.com/spreadsheets/d/1uGEMDAMG0gg0ye39r2UNICfS8tpuOsGJXS7MlWKUVZk/edit#gid=0)

Done

**Comment by JahnsMichael** [comment]
> Noice
> 
> NIT: I think it would be better if the `Decoration` folder was changed to `House Decoration`, wdyt?

Done, with pascal case, HouseDecorations

**Review by RaiRiz — APPROVED** [review]
Splendid. Approved!

**Review by ahmadhaydar — COMMENTED** [review]
Approb

**Pull request merged**
