### PR TITLE
[Rework] House Abigail Map

### LINKED ISSUE #333: Rework House Abigail Map
Adjust to excalidraw design
Share in 1 branch, bagi2 ruangan

After finished, setup stage builder (world points, ghost transition zones)

### PR DESCRIPTION
**Pull request by VadimBhirawa**
### Main changes
- Reworked House Abigail to fit the new layout

### Tasks List
- [close #333 ]

### Attachments
- 
image

### Notes
- The finished map might not look exactly like in the new layout/denah, it's cause I had to make the building more "squared".

### CODE REVIEW

**Review by JahnsMichael — CHANGES_REQUESTED** [review]
image

There are a lot of "overlapping faces" in the scene. Those overlapping faces may be okay right now because we are only using one material per mesh but it will be a problem when we apply two different materials (which we will), you can see the problem in the image attached. For now, I asked for a change first, but if you want to change it in another future issue, I will resolve it. Please let me know.

**Review by rafiftaris — CHANGES_REQUESTED** [review]
- hide the stair wall with another wall gameobject, so it can be textured differently
image


- these stairs should also be above ceilings
image


-

**Review by rafiftaris — CHANGES_REQUESTED** [review]
Wrong Transition Zone/Endpoints:
- Zone 2nd Floor Hallway - Stairway: 2nd Floor Hallway
- Zone Bathroom 1 - 2nd Floor Hallway

**Review by rafiftaris — APPROVED** [review]
stage builder points are all good 👍

**Review by uciii — APPROVED** [review]
Minor suggestion, sebenernya yang gw maksud posisi kamarmandi yang diluar jadi gini dim 
image
Keterangann (M = master bed, B = bathroom yang diluar)

kalo menurut lu udah oke kayak sekarang gpp, biar nggk terlalu gede aja lorong luarnya

**Review by JahnsMichael — APPROVED** [review]
LGTM!

**Pull request merged**
