### PR TITLE
[refactor] renaming project assets

### LINKED ISSUE #112: Refactor all project naming convention

### PR DESCRIPTION
**Pull request by raihansyahdean**
### Main changes
- Refactor some test scripts
- Refoldering, renaming, restructure all assets in project

### Tasks List
- [close #112 ]

### Attachments
image

### New Packages
N/A

### Resources 
- [Unity Style Guide](https://github.com/justinwasilenko/Unity-Style-Guide#scene-structure)

### CODE REVIEW

**Review by uciii — APPROVED** [review]
Gas

**Review by rafiftaris — APPROVED** [review]
kata dean approve2 aja

**Comment by RaiRiz** [comment]
apik!

**Review by JahnsMichael — APPROVED** [review]

**Review by RaiRiz — APPROVED** [review]

**Review by VadimBhirawa — APPROVED** [review]
Best!

**Pull request merged**
