### PR TITLE
[refactor] House Abigail Components Adjustment

### LINKED ISSUE #218: Adjust position of house abigail component
- position value angkanya gaboleh jelek (> 1 angka di belakang koma)
- pastiin titik2 RoomPoint juga di tengah2 ruangan biar ghost bisa roaming

### PR DESCRIPTION
**Pull request by VadimBhirawa**
### Main changes
Adjusted house abigail walls' position so that it is only one number behind the decimal (2.3, 7.2, etc).

### Tasks List
- [close #218 ]

### Attachments
- Living Room
image
- Master Room
image
- Bathroom
image
- Bedroom
image
- Kitchen
image
- Dining Room
image
- Family Room
image
- Garage
image
- Laundry Room
image
- Basement
image
- 2nd Floor
image
- Outdoor
image

### CODE REVIEW

**Review by JahnsMichael — APPROVED** [review]
All walls' position is positioned well and only one number behind the decimal. Good job!

**Review by uciii — CHANGES_REQUESTED** [review]
- Change SO to one number behind the decimal
- Revisit floor coordinate and SO for Basement, seems like there is a big different there

**Review by uciii — APPROVED** [review]
👍

**Review by raihansyahdean — CHANGES_REQUESTED** [review]
- Please delete the HouseAbigail prefab from _Levels/_Builder/HouseAbigail
- Adjust the HouseAbigail_Builder scene, copy all the building objects from your development scene
- Update the Maps scene HouseAbigail_Adjustment_Outdoor using your corrected buildings.
- Make sure the StageManager is included in the scene as well

**Review by raihansyahdean — APPROVED** [review]
Cool

**Pull request merged**
