### PR TITLE
[World Building] Living, Dining, Kitchen

### LINKED ISSUE #309: [Env Build] Kitchen Room

### LINKED ISSUE #363: [World Building] Insert Living room objects

### LINKED ISSUE #364: [World Building] Insert Doors
On all parts of the house

### PR DESCRIPTION
**Pull request by JahnsMichael**
### Main changes

- add decors to living room, dining room, and kitchen
- add doors

### Tasks List

- [close #363]
- [close #309]
- [close #364]

### Attachments

> Note that my recordings seem to be very laggy, please manually review this PR by opening the scene directly from Unity

#### Living Room

[Screencast from 17-07-22 17:16:37.webm](https://user-images.githubusercontent.com/60375650/179393960-242b0add-caf3-4b69-925b-1c75959f4174.webm)

#### Dining Room and Kitchen

[Screencast from 17-07-22 17:20:18.webm](https://user-images.githubusercontent.com/60375650/179394114-ef6cf1fa-3c1d-4197-886e-ec69843653d9.webm)

### CODE REVIEW

**Review by VadimBhirawa — APPROVED** [review]
LGTM!

**Comment by JahnsMichael** [comment]
> Great Prefab(ssss)
> 
> Small comment, some prefabs are not in the right folder
> 
> * vase_petit prefab outside the folder (same as wine bottles)
> * wineglass is inside wine bottle not the folder
>   image

It is actually intended, that each prefab that comes from an outside source like the Sketchfab plugin have its own directory structure and it is already properly structured from my perspective, so I choose to preserve it. But the prefab will be hard to find if I leave it in its directory, it will have additional effort for access the prefab. So I move the main prefab to its parent, for example:

```
Props/
⎣_ WineBottles/
     ⎣_ materials/                 (contains WineBottles' materials)
     ⎣_ meshes/                    (contains WineBottles' meshes)
     ⎣_ textures/                  (contains WineBottles' textures)
⎣_ WineBottles.prefab              (the actual prefab)
```

This directory structure can minimize the effort of accessing the actual prefab and encapsulate the "details" like materials, meshes, and textures that we usually don't really care except for a specific purpose that is unlikely to happen. I just find it today but this directory structure has a proper term called "Fractal Structure", originally used for React projects for managing UI components. We can see the similarity between components in a React project and prefab in a Unity project. More on that in this [blog about Fractal Structure](https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af). We can really see the benefit of this structure if we look at the project window in the Unity Editor. It will be easier to just see the preview of each prefab and grab the prefab from the Props directory than have to dig inside each child to find the one we want.

image

For the WineGlasses prefab, it is not inside the WineBottles directory but at the same level. Maybe the GitHub file tree UI makes it confusing but you can see in the gif below that `WineGlasses.prefab` is outside of `WineBottles/` directory.

Peek 2022-07-20 13-23

It is a matter of convention I guess, so, wdyt? I will refactor it if it is necessary.

**Review by rafiftaris — APPROVED** [review]
great job! for the file naming and placement convention, i have no problem with it

**Review by uciii — APPROVED** [review]
LG!!!!

**Pull request merged**
