### PR TITLE
[Feature] adding icon for interactable item

### LINKED ISSUE #37: Add guiding icon to light switch
Include animation (2 frames looping)
Icon dari asset LimeZu

### PR DESCRIPTION
**Pull request by naufalhilmi12345**
### Main changes

- adding new icon for guiding interactable thing
- [Issue] making icon 3d
- [Issue] changing audio system

### Tasks List

- [close #37 ]

### Attachments

https://user-images.githubusercontent.com/44135006/148634199-7a1c45eb-2ff1-4531-9abe-c1e34d05a72e.mp4

### CODE REVIEW

**Comment by ahmadhaydar** [comment]
Oh kewl

**Comment by ahmadhaydar** [comment]
Yeah

**Review by raihansyahdean — APPROVED** [review]
Nice

**Review by rafiftaris — APPROVED** [review]
Good

**Pull request merged**
