### PR TITLE
Add Volumetric Fog to Global Volume prefab

### LINKED ISSUE #96: Add Volumetric Fog to Global Volume prefab

### PR DESCRIPTION
**Pull request by VadimBhirawa**
### Main changes
Added Volumetric Fog as Child of Global Volume and extracted as prefab

### Tasks List
Link your Card to the PR by adding description: KEYWORD #CARD-NUMBER >
- [close #96 ]

### Attachments
image

### CODE REVIEW

**Review by raihansyahdean — CHANGES_REQUESTED** [review]
Rename Global Volume prefab to "Astral Global Volume"

**Review by RaiRiz — APPROVED** [review]
looks good!

**Review by uciii — APPROVED** [review]
👍

**Review by raihansyahdean — APPROVED** [review]
Good job!

**Pull request merged**
