### PR TITLE
[refactor] Split House Abigail Rooms with Probuilder and Progrid

### LINKED ISSUE #38: Split Floors and Walls in House Abigail

### PR DESCRIPTION
**Pull request by VadimBhirawa**
### Main changes
Split the House Abigail map into different objects. The objects are divided by rooms, and each room have at least 1 Floor Object, and 1 Walls parent object. The walls parent object usually have 3-4 Wall object inside of it. Some rooms have a Roof Object too.

### Tasks List
- [close #38]

### Attachments
image

### CODE REVIEW

**Review by uciii — COMMENTED** [review]
general
     - old building grouping
lt 2
     - there is a sloping roof
lt 1
     - grouping all rooms on the 1st floor
     - there is a laundry room that doesn't fit if the kitchen is hidden
     - wall 2 kitchen not fit (looks from family room)
     - adjust floor for dining and kitchen
     - split the bed room wall so it's half bed and half dinning

**Review by uciii — COMMENTED** [review]
- Adjust kitchen and dinning room roof
- Adjust Wall 2 living room

**Review by uciii — APPROVED** [review]
Looks Good! 👍

**Review by JahnsMichael — APPROVED** [review]
Looks good. Asumsi yang "Unused" emang sengaja gak diapus dulu kan ya.

**Pull request merged**
