### PR TITLE
[feature] House Abigail Light Source

### LINKED ISSUE #39: Add lights in House Abigail

### PR DESCRIPTION
**Pull request by uciii**
### Main changes
Add light source in all rooms of House Abigail

### Tasks List
- [close #39 ]

### Attachments
https://user-images.githubusercontent.com/71260420/149750827-8ea1d737-9360-4245-bfe9-ca00e3d7c425.mp4

### CODE REVIEW

**Review by JahnsMichael — COMMENTED** [review]
Ini kayaknya penempatan Light Source nya agak mepet ke tembok gitu, kayaknya karena penempatan Light Source nya fixed gitu ya di prefab? (edit : expected)

**Review by VadimBhirawa — COMMENTED** [review]
image
This switch looks a bit weird cause it's more bulky than the other switches.

**Review by JahnsMichael — APPROVED** [review]

**Comment by VadimBhirawa** [comment]
image
Don't forget to change the camera angles. Look at other scenes in the development branch for reference.

**Review by VadimBhirawa — APPROVED** [review]
Looks good!

**Pull request merged**
